import type { AgentBlueprint, AgentRegistration } from "@alfy2/shared";

/**
 * Deterministic file templates for generated agents. Pure string/JSON assembly — no I/O.
 * The factory writes these via a FileWriter port.
 */

/** "business.followup" -> "business_followup" (folder/module name). */
export function familyFromKey(key: string): string {
  return key.replace(/\./g, "_");
}

export function renderConfigJson(blueprint: AgentBlueprint, reg: AgentRegistration): string {
  const config = {
    key: blueprint.key,
    version: blueprint.version,
    runtime: blueprint.runtime,
    description: blueprint.description,
    capabilities: blueprint.capabilities,
    endpoint: reg.endpoint,
    tools: blueprint.tools,
    memory_scope: blueprint.memory_scope,
    permissions: blueprint.permissions,
    task_queue: blueprint.task_queue,
    success_metrics: blueprint.success_metrics,
    dashboard_card: blueprint.dashboard_card,
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

export function renderInitPy(blueprint: AgentBlueprint): string {
  return `"""${blueprint.key} agent — generated by the Alfy2 Agent Factory.\n\n${blueprint.description}\nThis agent is stateless and side-effect-free except via returned next_actions; irreversible\ncapabilities must pass through the Approval Gate.\n"""\n`;
}

export function renderAgentPy(blueprint: AgentBlueprint, family: string): string {
  const caps = blueprint.capabilities.map((c) => `    # - ${c}`).join("\n");
  return `"""Worker entrypoint for the ${blueprint.key} agent.

Implements the Task contract: receives a Task, returns a SignalToAction result.
Capabilities:
${caps}

GUARDRAIL: capabilities in permissions.requires_approval_for must NOT be executed here;
they are returned as irreversible next_actions for the Approval Gate.
"""
from __future__ import annotations

from typing import Any

AGENT_KEY = "${blueprint.key}"
FAMILY = "${family}"


def run(task: dict[str, Any]) -> dict[str, Any]:
    """Handle one Task. Replace the placeholder logic with the real implementation."""
    capability = task.get("capability", "")
    return {
        "what_changed": f"Received {capability} task for {AGENT_KEY}.",
        "why_it_matters": "Placeholder — implement the real ${blueprint.key} logic.",
        "next_actions": [],
        "confidence": 0.0,
        "evidence": [],
        "explanation": "Generated stub. No work performed yet.",
    }
`;
}

export function renderInstructionsMd(blueprint: AgentBlueprint): string {
  const metrics = blueprint.success_metrics
    .map((m) => `- **${m.name}** (${m.target}): ${m.description}`)
    .join("\n");
  const approvals = blueprint.permissions.requires_approval_for.length
    ? blueprint.permissions.requires_approval_for.map((c) => `\`${c}\``).join(", ")
    : "none";
  return `# ${blueprint.key} — Instructions

${blueprint.description}

## Operating instructions
${blueprint.instructions}

## Capabilities
${blueprint.capabilities.map((c) => `- ${c}`).join("\n")}

## Memory scope
- Reads: ${blueprint.memory_scope.can_read ? "yes" : "no"} | Writes: ${blueprint.memory_scope.can_write ? "yes" : "no"}
- Kinds: ${blueprint.memory_scope.kinds.join(", ") || "(none)"} | Max items: ${blueprint.memory_scope.max_items}

## Permissions
- Network: ${blueprint.permissions.network} | Irreversible actions: ${blueprint.permissions.irreversible_actions}
- Requires approval for: ${approvals}

## Success metrics
${metrics || "- (none defined)"}
`;
}

export function renderTestPy(blueprint: AgentBlueprint, family: string): string {
  return `"""Generated tests for the ${blueprint.key} agent."""
from alfy_workers.${family}.agent import run, AGENT_KEY


def test_agent_key():
    assert AGENT_KEY == "${blueprint.key}"


def test_run_returns_signal_to_action():
    result = run({"capability": "${blueprint.capabilities[0]}", "input": {}})
    # Must return a Signal->Action-shaped dict with a non-empty explanation.
    assert set(["what_changed", "why_it_matters", "next_actions", "explanation"]).issubset(result)
    assert result["explanation"]
`;
}

export function renderDocMd(blueprint: AgentBlueprint, family: string): string {
  return `# ${blueprint.dashboard_card.title} (\`${blueprint.key}\`)

${blueprint.description}

- **Runtime:** ${blueprint.runtime}
- **Version:** ${blueprint.version}
- **Folder:** \`workers/alfy_workers/${family}/\`
- **Task queue:** \`${blueprint.task_queue.name}\` (concurrency ${blueprint.task_queue.max_concurrency}, retries ${blueprint.task_queue.retry_limit})

## Capabilities
${blueprint.capabilities.map((c) => `- ${c}`).join("\n")}

## Tools
${blueprint.tools.map((t) => `- \`${t.name}\` — ${t.description}`).join("\n") || "- (none)"}

## Success metrics
${blueprint.success_metrics.map((m) => `- **${m.name}** — target ${m.target}`).join("\n") || "- (none)"}

> Generated by the Alfy2 Agent Factory after operator approval. See docs/AGENT_FACTORY.md.
`;
}
